Set the installation prefix for CMake

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -52,7 +52,7 @@ install_ccache() {
     else
       mkdir build
       cd build
-      cmake -DCMAKE_BUILD_TYPE=Release -DZSTD_FROM_INTERNET=yes .. >/dev/null || fail "Could not configure CMake"
+      cmake -DCMAKE_INSTALL_PREFIX="$install_path" -DCMAKE_BUILD_TYPE=Release -DZSTD_FROM_INTERNET=yes .. >/dev/null || fail "Could not configure CMake"
     fi
 
     echo "∗ Compiling..."
